apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-project
  labels:
    app: rag-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rag-project
  template:
    metadata:
      labels:
        app: rag-project
    spec:
      containers:
      - name: rag-project
        image: your-docker-image:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENV_VARIABLE_NAME
          valueFrom:
            configMapKeyRef:
              name: rag-project-config
              key: ENV_VARIABLE_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"