apiVersion: v1
kind: Service
metadata:
  name: rag-service
  labels:
    app: rag-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: rag-app